spring:
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/kemao_3?useSSL=false&serverTimezone=CST&allowPublicKeyRetrieval=true
      username: kemao_3
      password: 1234
   redis:
      host: 127.0.0.1
      port: 6379
      database: 0

server.port: 8092
