# 配置数据源
spring:
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/ZYF?useSSL=false&serverTimezone=CST&allowPublicKeyRetrieval=true
      username: ZYF
      password: 1234
   jpa:
      generate-ddl: true
      show-sql: true
   redis:
      host: 127.0.0.1
      port: 6379
      database: 0